"""Add weightclass and match models with relationships

Revision ID: 9798465ea326
Revises: e6ce46ed7884
Create Date: 2025-01-12 20:14:37.735685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9798465ea326'
down_revision = 'e6ce46ed7884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_classes')
    op.drop_table('matches')
    op.drop_table('fighters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('weight_class', sa.VARCHAR(length=255), nullable=False),
    sa.Column('wins', sa.INTEGER(), nullable=True),
    sa.Column('draws', sa.INTEGER(), nullable=True),
    sa.Column('losses', sa.INTEGER(), nullable=True),
    sa.Column('height_cm', sa.FLOAT(), nullable=True),
    sa.Column('weight_kg', sa.FLOAT(), nullable=True),
    sa.Column('reach_cm', sa.FLOAT(), nullable=True),
    sa.Column('stance', sa.VARCHAR(length=255), nullable=True),
    sa.Column('significant_strikes_landed_per_minute', sa.FLOAT(), nullable=True),
    sa.Column('significant_striking_accuracy', sa.FLOAT(), nullable=True),
    sa.Column('significant_strikes_absorbed_per_minute', sa.FLOAT(), nullable=True),
    sa.Column('significant_strike_defence', sa.FLOAT(), nullable=True),
    sa.Column('average_takedowns_landed_per_15_minutes', sa.FLOAT(), nullable=True),
    sa.Column('takedown_accuracy', sa.FLOAT(), nullable=True),
    sa.Column('takedown_defense', sa.FLOAT(), nullable=True),
    sa.Column('average_submissions_attempted_per_15_minutes', sa.FLOAT(), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('fighter_1_id', sa.INTEGER(), nullable=False),
    sa.Column('fighter_2_id', sa.INTEGER(), nullable=False),
    sa.Column('fighter_1_kd', sa.INTEGER(), nullable=True),
    sa.Column('fighter_2_kd', sa.INTEGER(), nullable=True),
    sa.Column('fighter_1_str', sa.INTEGER(), nullable=True),
    sa.Column('fighter_2_str', sa.INTEGER(), nullable=True),
    sa.Column('fighter_1_td', sa.INTEGER(), nullable=True),
    sa.Column('fighter_2_td', sa.INTEGER(), nullable=True),
    sa.Column('fighter_1_sub', sa.INTEGER(), nullable=True),
    sa.Column('fighter_2_sub', sa.INTEGER(), nullable=True),
    sa.Column('weight_class_id', sa.INTEGER(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('round', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.VARCHAR(length=10), nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('winner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fighter_1_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['fighter_2_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['fighters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('min_weight', sa.FLOAT(), nullable=False),
    sa.Column('max_weight', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
