"""Add weightclass and match models with relationships

Revision ID: e6ce46ed7884
Revises: d4e940eb38ca
Create Date: 2025-01-12 19:38:12.377490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ce46ed7884'
down_revision = 'd4e940eb38ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_weight', sa.Float(), nullable=False),
    sa.Column('max_weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('fighter_1_id', sa.Integer(), nullable=False),
    sa.Column('fighter_2_id', sa.Integer(), nullable=False),
    sa.Column('fighter_1_kd', sa.Integer(), nullable=True),
    sa.Column('fighter_2_kd', sa.Integer(), nullable=True),
    sa.Column('fighter_1_str', sa.Integer(), nullable=True),
    sa.Column('fighter_2_str', sa.Integer(), nullable=True),
    sa.Column('fighter_1_td', sa.Integer(), nullable=True),
    sa.Column('fighter_2_td', sa.Integer(), nullable=True),
    sa.Column('fighter_1_sub', sa.Integer(), nullable=True),
    sa.Column('fighter_2_sub', sa.Integer(), nullable=True),
    sa.Column('weight_class_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fighter_1_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['fighter_2_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['fighters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('weight_classes')
    # ### end Alembic commands ###
